service: airkeeper

provider:
  name: aws
  # region: ${opt:region}
  # stage: ${opt:stage}
  runtime: nodejs14.x
  memorySize: 512
  logRetentionInDays: 14
  environment: ${file(load-secrets-env.js)}

package:
  patterns:
    - 'config/*.json'

functions:
  rrp-beacon-update:
    handler: dist/src/handlers/rrp.handler
    timeout: 60
    events:
      - schedule: rate(1 minute)
  psp-beacon-update:
    handler: dist/src/handlers/psp.handler
    timeout: 60
    events:
      - schedule: rate(1 minute)
