service: airkeeper

provider:
  name: aws
  region: ${env:REGION, 'us-east-1'}
  stage: ${env:STAGE, 'dev'}
  runtime: nodejs14.x
  memorySize: 512
  logRetentionInDays: 14
  environment: ${file(load-secrets-env.js)}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: 'arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-process-subscriptions'

package:
  patterns:
    - 'config/*.json'

functions:
  rrp-beacon-update:
    handler: dist/src/handlers/rrp.handler
    timeout: 60
    events:
      - schedule: rate(1 minute)
  psp-beacon-update:
    handler: dist/src/handlers/psp.handler
    environment:
      CLOUD_PROVIDER: ${self:provider.name}
    timeout: 60
    events:
      - schedule: rate(1 minute)
  process-subscriptions:
    handler: dist/src/handlers/process-subscriptions.handler
    timeout: 15
