service: airkeeper

plugins:
  - serverless-plugin-typescript

variablesResolutionMode: 20210326

provider:
  name: aws
  # region: ${opt:region}
  # stage: ${opt:stage}
  runtime: nodejs14.x
  memorySize: 512
  lambdaHashingVersion: 20201221
  logRetentionInDays: 14
  environment: ${file(load-secrets-env.js)}

package:
  patterns:
    - 'config/*.json'

functions:
  start:
    handler: src/start.handler
    name: airkeeper-update-beacon
    timeout: 60
    events:
      - schedule: rate(1 minute)
