name: Continuous Build

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone Airkeeper
        uses: actions/checkout@v2
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/mlc_config.json

  compile:
    name: Build Airkeeper
    runs-on: ubuntu-latest
    steps:
      - name: Clone Airkeeper
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Compile
        run: yarn compile

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Clone Airkeeper
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
